name: AESD Assignment 4 Part 1 Unit Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-test:
    runs-on: self-hosted

    container:
      image: cuaesd/aesd-autotest:24-assignment3

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Run unit tests
        run: ./unit-test.sh

