name: AESD Assignment 3 Autotest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit-test:
    runs-on: self-hosted

    container:
      image: cuaesd/aesd-autotest:24-assignment3

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install missing toolchain
        run: |
          apt-get update
          apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          which aarch64-linux-gnu-gcc
          aarch64-linux-gnu-gcc --version

      - name: Run unit tests
        run: ./unit-test.sh

  full-test:
    runs-on: self-hosted

    container:
      image: cuaesd/aesd-autotest:24-assignment3

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install missing toolchain
        run: |
          apt-get update
          apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
          which aarch64-linux-gnu-gcc
          aarch64-linux-gnu-gcc --version

      - name: Run full test
        run: ./full-test.sh

